version: "3.6"

services:
  go:
    image: golang:1.19
    tty: true
    volumes:
      - ./go:/exercismgo:Z
    working_dir: /exercismgo

  java:
    image: eclipse-temurin:17
    tty: true
    volumes:
      - ./java:/exercismjava:Z
    working_dir: /exercismjava
